name: Quality Control

on:
  push:
    paths:
      - ".github/workflows/qa.yml"
  pull_request:
    branches:
      - main

defaults:
  run:
    shell: bash

jobs:
  check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@stable

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Check Formatting
        run: |
          cargo +${{ steps.rust-install.outputs.name }} fmt --check

      - name: Check with Clippy
        run: |
          cargo +${{ steps.rust-install.outputs.name }} clippy -- -D warnings

      - name: Check docs
        run: |
          cargo +${{ steps.rust-install.outputs.name }} rustdoc -- -D warnings

  test:
    strategy:
      matrix:
        rust-toolchain:
          - stable
          - nightly
          - 1.74.0
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install rust
        id: rust-install
        uses: dtolnay/rust-toolchain@master
        with:
          toolchain: ${{ matrix.rust-toolchain }}

      - name: Cache
        uses: Swatinem/rust-cache@v2

      - name: Test
        run: |
          cargo +${{ steps.rust-install.outputs.name }} test

  actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Install action-validator with asdf
        uses: asdf-vm/actions/install@v3
        with:
          tool_versions: |
            action-validator 0.5.1

      - name: Lint Actions
        run: |
          find .github/workflows -type f \( -iname \*.yaml -o -iname \*.yml \) \
            | xargs -I {} action-validator --verbose {}
